name: portfolio
services:
  website:
    image: node
    wordking_dir: /
    restart: always
    ports:
      - "${WEBSITE_PORT}:3000"
    volumes:
      - ./:/
    entrypoint: ["sh", "-c", "chmod +x ./entrypoint.sh && ./entrypoint.sh"]
