name: portfolio
services:
  website:
    image: node
    working_dir: /app
    restart: always
    ports:
      - "${WEBSITE_PORT}:3000"
    volumes:
      - ./:/app
    entrypoint: ["sh", "-c", "chmod +x ./entrypoint.sh && ./entrypoint.sh"]
